option to start glassfish in debug mode
logicalclocks/chef-glassfish pull request #15
Opened 2022-03-04 16:14 UTC by jimdowling

Devtooling - start glassfish in debug mode

2022-03-07 08:20 UTC, robzor92 requested changes

2022-03-07 08:20 UTC, robzor92 commented on attributes/default.rb
> +
No actual change here

2022-03-07 08:43 UTC, jimdowling commented on attributes/default.rb
> +
removed

2022-03-08 13:30 UTC, robzor92 approved these changes

2022-03-08 17:46 UTC, merged